#!/usr/bin/env python3
"""
Speculative Generation Engine

Draft-verify pattern: a fast model generates a draft response, then a larger
model verifies and optionally corrects it. This is mutually exclusive with
cascading inference -- the user picks one strategy at a time.

Flow:
  1. Draft phase -- Fast model generates a complete response draft.
  2. Verify phase -- Larger model evaluates the draft and either:
     - Approves it (minor edits only) -> serve as final.
     - Rejects it -> larger model generates its own response.
  3. Optional convergence loop -- If draft and verify differ significantly,
     iterate (up to max_iterations) until responses converge or limit reached.
"""

import logging
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any

import yaml

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Quality evaluation import (from self_correction.py)
# ---------------------------------------------------------------------------

try:
    from opti_oignon.self_correction import compute_heuristic_quality  # noqa: F401
    QUALITY_EVAL_AVAILABLE = True
except ImportError:
    QUALITY_EVAL_AVAILABLE = False

# ---------------------------------------------------------------------------
# Ollama import
# ---------------------------------------------------------------------------

try:
    import ollama as _ollama
    OLLAMA_AVAILABLE = True
except ImportError:
    OLLAMA_AVAILABLE = False
    _ollama = None

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_CONFIG_DIR = Path(__file__).parent / "config"
_DEFAULT_CONFIG_PATH = _CONFIG_DIR / "speculative.yaml"

_VERIFY_SYSTEM_PROMPT = """You are a verification assistant. You will be given a user query and a draft response generated by another model. Your task is to evaluate the draft and either:
1. If the draft is correct and complete, reproduce it with minor improvements only.
2. If the draft contains errors, is incomplete, or is low quality, generate a better response from scratch.

Be concise and accurate. Focus on correctness over style."""


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class SpeculativeResult:
    """Result of a speculative generation run."""
    final_response: str
    draft_response: str
    verify_response: str
    draft_model: str
    verify_model: str
    draft_accepted: bool
    iterations: int
    total_latency_ms: float
    draft_latency_ms: float
    verify_latency_ms: float
    convergence_score: float


# ---------------------------------------------------------------------------
# Convergence / similarity utilities
# ---------------------------------------------------------------------------


def compute_similarity(text_a: str, text_b: str) -> float:
    """Compute heuristic similarity between two texts.

    Uses word overlap (Jaccard similarity) combined with length ratio
    to estimate how similar two responses are.

    Args:
        text_a: First text.
        text_b: Second text.

    Returns:
        Similarity score between 0.0 and 1.0.
    """
    if not text_a or not text_b:
        return 0.0

    words_a = set(text_a.lower().split())
    words_b = set(text_b.lower().split())

    if not words_a or not words_b:
        return 0.0

    # Jaccard similarity
    intersection = words_a & words_b
    union = words_a | words_b
    jaccard = len(intersection) / len(union) if union else 0.0

    # Length ratio penalty
    len_a = len(text_a)
    len_b = len(text_b)
    length_ratio = min(len_a, len_b) / max(len_a, len_b) if max(len_a, len_b) > 0 else 0.0

    # Combined score (weighted)
    return 0.7 * jaccard + 0.3 * length_ratio


# ---------------------------------------------------------------------------
# SpeculativeGenerator
# ---------------------------------------------------------------------------


def _extract_message_content(response: Any) -> str:
    """Extract assistant text from an ollama chat response.

    Handles both dict responses and object (ChatResponse) responses returned by
    newer ollama clients, mirroring CascadingInference._call_llm. The previous
    dict-only `response["message"]["content"]` raised on the object form, which
    `generate()` caught as a failed draft/verify.
    """
    if isinstance(response, dict):
        return response.get("message", {}).get("content", "") or ""
    msg = getattr(response, "message", None)
    if msg is not None:
        if hasattr(msg, "content"):
            return msg.content or ""
        if isinstance(msg, dict):
            return msg.get("content", "") or ""
    return ""


class SpeculativeGenerator:
    """Speculative generation engine with draft-verify loop.

    A fast model generates a draft; a larger model verifies it. If the
    draft meets the convergence threshold, it is served directly. Otherwise,
    the verifier produces a corrected response. The loop can iterate up to
    max_iterations times.
    """

    def __init__(self, config_path: str | Path | None = None):
        """Initialize from YAML config.

        Args:
            config_path: Path to speculative.yaml. If None, uses default location.
        """
        self._config_path = Path(config_path) if config_path else _DEFAULT_CONFIG_PATH
        self._raw_config: dict = {}
        self._enabled: bool = False
        self._draft_model: str = "qwen3:8b"
        self._verify_model: str = "qwen3:32b"
        self._max_iterations: int = 2
        self._convergence_threshold: float = 0.85
        self._draft_max_tokens: int = 2048
        self._verify_max_tokens: int = 4096
        self._draft_temperature: float = 0.5
        self._verify_temperature: float = 0.3
        self._last_result: SpeculativeResult | None = None
        self._load_config()

    # ------------------------------------------------------------------
    # Config
    # ------------------------------------------------------------------

    def _load_config(self) -> None:
        """Load configuration from YAML file."""
        if self._config_path.exists():
            try:
                with open(self._config_path, encoding="utf-8") as f:
                    raw = yaml.safe_load(f) or {}
                self._raw_config = raw
                self._enabled = raw.get("enabled", False)
                self._draft_model = raw.get("draft_model", "qwen3:8b")
                self._verify_model = raw.get("verify_model", "qwen3:32b")
                self._max_iterations = raw.get("max_iterations", 2)
                self._convergence_threshold = raw.get("convergence_threshold", 0.85)
                self._draft_max_tokens = raw.get("draft_max_tokens", 2048)
                self._verify_max_tokens = raw.get("verify_max_tokens", 4096)
                self._draft_temperature = raw.get("draft_temperature", 0.5)
                self._verify_temperature = raw.get("verify_temperature", 0.3)
                logger.info(
                    "Speculative config loaded: enabled=%s, draft=%s, verify=%s",
                    self._enabled, self._draft_model, self._verify_model,
                )
            except Exception as e:
                logger.error("Failed to load speculative config: %s", e)
                self._set_defaults()
        else:
            logger.warning(
                "Speculative config not found at %s, using defaults",
                self._config_path,
            )
            self._set_defaults()

    def _set_defaults(self) -> None:
        """Set default configuration values."""
        self._enabled = False
        self._draft_model = "qwen3:8b"
        self._verify_model = "qwen3:32b"
        self._max_iterations = 2
        self._convergence_threshold = 0.85
        self._draft_max_tokens = 2048
        self._verify_max_tokens = 4096
        self._draft_temperature = 0.5
        self._verify_temperature = 0.3

    def _save_config(self) -> None:
        """Persist current config to YAML."""
        data = {
            "enabled": self._enabled,
            "draft_model": self._draft_model,
            "verify_model": self._verify_model,
            "max_iterations": self._max_iterations,
            "convergence_threshold": self._convergence_threshold,
            "draft_max_tokens": self._draft_max_tokens,
            "verify_max_tokens": self._verify_max_tokens,
            "draft_temperature": self._draft_temperature,
            "verify_temperature": self._verify_temperature,
        }
        try:
            self._config_path.parent.mkdir(parents=True, exist_ok=True)
            with open(self._config_path, "w", encoding="utf-8") as f:
                yaml.safe_dump(data, f, default_flow_style=False, sort_keys=False)
            logger.debug("Speculative config saved to %s", self._config_path)
        except Exception as e:
            logger.error("Failed to save speculative config: %s", e)

    # ------------------------------------------------------------------
    # Properties
    # ------------------------------------------------------------------

    @property
    def enabled(self) -> bool:
        return self._enabled

    @enabled.setter
    def enabled(self, value: bool) -> None:
        self._enabled = bool(value)

    @property
    def draft_model(self) -> str:
        return self._draft_model

    @property
    def verify_model(self) -> str:
        return self._verify_model

    @property
    def max_iterations(self) -> int:
        return self._max_iterations

    @property
    def convergence_threshold(self) -> float:
        return self._convergence_threshold

    @property
    def last_result(self) -> SpeculativeResult | None:
        return self._last_result

    # ------------------------------------------------------------------
    # Config update
    # ------------------------------------------------------------------

    def get_config(self) -> dict:
        """Return current configuration as a dictionary."""
        return {
            "enabled": self._enabled,
            "draft_model": self._draft_model,
            "verify_model": self._verify_model,
            "max_iterations": self._max_iterations,
            "convergence_threshold": self._convergence_threshold,
            "draft_max_tokens": self._draft_max_tokens,
            "verify_max_tokens": self._verify_max_tokens,
            "draft_temperature": self._draft_temperature,
            "verify_temperature": self._verify_temperature,
        }

    def update_config(
        self,
        enabled: bool | None = None,
        draft_model: str | None = None,
        verify_model: str | None = None,
        max_iterations: int | None = None,
        convergence_threshold: float | None = None,
        draft_max_tokens: int | None = None,
        verify_max_tokens: int | None = None,
        draft_temperature: float | None = None,
        verify_temperature: float | None = None,
    ) -> None:
        """Update configuration fields and persist to YAML.

        Only non-None fields are updated; others remain unchanged.
        """
        if enabled is not None:
            self._enabled = bool(enabled)
        if draft_model is not None:
            self._draft_model = str(draft_model)
        if verify_model is not None:
            self._verify_model = str(verify_model)
        if max_iterations is not None:
            self._max_iterations = max(1, int(max_iterations))
        if convergence_threshold is not None:
            self._convergence_threshold = max(0.0, min(1.0, float(convergence_threshold)))
        if draft_max_tokens is not None:
            self._draft_max_tokens = max(256, int(draft_max_tokens))
        if verify_max_tokens is not None:
            self._verify_max_tokens = max(256, int(verify_max_tokens))
        if draft_temperature is not None:
            self._draft_temperature = max(0.0, min(2.0, float(draft_temperature)))
        if verify_temperature is not None:
            self._verify_temperature = max(0.0, min(2.0, float(verify_temperature)))

        self._save_config()
        logger.info(
            "Speculative config updated: enabled=%s, draft=%s, verify=%s",
            self._enabled, self._draft_model, self._verify_model,
        )

    # ------------------------------------------------------------------
    # LLM calls
    # ------------------------------------------------------------------

    def _call_draft(self, query: str) -> str:
        """Call the draft model via Ollama.

        Args:
            query: User query.

        Returns:
            Draft response text.
        """
        if not OLLAMA_AVAILABLE or _ollama is None:
            raise RuntimeError("Ollama is not available for draft generation")

        response = _ollama.chat(
            model=self._draft_model,
            messages=[{"role": "user", "content": query}],
            options={
                "temperature": self._draft_temperature,
                "num_predict": self._draft_max_tokens,
            },
        )
        return _extract_message_content(response)

    def _call_verify(self, query: str, draft: str) -> str:
        """Call the verify model via Ollama to evaluate/correct the draft.

        Args:
            query: Original user query.
            draft: Draft response to verify.

        Returns:
            Verified response text.
        """
        if not OLLAMA_AVAILABLE or _ollama is None:
            raise RuntimeError("Ollama is not available for verification")

        verify_prompt = (
            f"User query: {query}\n\n"
            f"Draft response:\n{draft}\n\n"
            "Evaluate the draft. If it is correct and complete, reproduce it "
            "with minor improvements. If it has errors or is incomplete, "
            "generate a better response."
        )

        response = _ollama.chat(
            model=self._verify_model,
            messages=[
                {"role": "system", "content": _VERIFY_SYSTEM_PROMPT},
                {"role": "user", "content": verify_prompt},
            ],
            options={
                "temperature": self._verify_temperature,
                "num_predict": self._verify_max_tokens,
            },
        )
        return _extract_message_content(response)

    # ------------------------------------------------------------------
    # Main generate method
    # ------------------------------------------------------------------

    def generate(
        self,
        query: str,
        task_type: str | None = None,
        draft_call: Any = None,
        verify_call: Any = None,
    ) -> SpeculativeResult:
        """Run speculative generation with draft-verify loop.

        Args:
            query: User query to process.
            task_type: Optional task type hint (reserved for future use).
            draft_call: Optional callable(query) -> str for testing.
                        If None, uses self._call_draft().
            verify_call: Optional callable(query, draft) -> str for testing.
                         If None, uses self._call_verify().

        Returns:
            SpeculativeResult with final response and all phase details.
        """
        draft_fn = draft_call if draft_call is not None else self._call_draft
        verify_fn = verify_call if verify_call is not None else self._call_verify

        total_start = time.time()
        draft_latency_total = 0.0
        verify_latency_total = 0.0

        # Phase 1: Generate draft
        draft_start = time.time()
        try:
            draft_response = draft_fn(query)
        except Exception as e:
            logger.error("Draft generation failed: %s", e)
            draft_response = ""
        draft_latency = (time.time() - draft_start) * 1000
        draft_latency_total += draft_latency

        if not draft_response:
            # Draft failed entirely; fall back to verify model directly
            verify_start = time.time()
            try:
                verify_response = verify_fn(query, "")
            except Exception as e:
                logger.error("Verify fallback also failed: %s", e)
                verify_response = f"[ERR] Both draft and verify failed: {e}"
            verify_latency = (time.time() - verify_start) * 1000
            verify_latency_total += verify_latency

            total_ms = (time.time() - total_start) * 1000
            result = SpeculativeResult(
                final_response=verify_response,
                draft_response="",
                verify_response=verify_response,
                draft_model=self._draft_model,
                verify_model=self._verify_model,
                draft_accepted=False,
                iterations=1,
                total_latency_ms=round(total_ms, 1),
                draft_latency_ms=round(draft_latency_total, 1),
                verify_latency_ms=round(verify_latency_total, 1),
                convergence_score=0.0,
            )
            self._last_result = result
            return result

        # Phase 2: Verify loop
        current_draft = draft_response
        verify_response = ""
        convergence = 0.0
        iterations = 0

        for iteration in range(self._max_iterations):
            iterations = iteration + 1

            verify_start = time.time()
            try:
                verify_response = verify_fn(query, current_draft)
            except Exception as e:
                logger.error("Verify iteration %d failed: %s", iterations, e)
                verify_response = current_draft  # Keep draft on verify failure
                break
            verify_latency = (time.time() - verify_start) * 1000
            verify_latency_total += verify_latency

            # Check convergence
            convergence = compute_similarity(current_draft, verify_response)
            logger.debug(
                "Speculative iteration %d: convergence=%.3f (threshold=%.3f)",
                iterations, convergence, self._convergence_threshold,
            )

            if convergence >= self._convergence_threshold:
                # Draft and verify are similar enough; accept draft
                logger.info(
                    "Speculative: draft accepted at iteration %d (convergence=%.3f)",
                    iterations, convergence,
                )
                break

            # Responses diverge; use verify response as new draft for next iteration
            current_draft = verify_response

        # Determine if draft was accepted
        draft_accepted = convergence >= self._convergence_threshold

        # Choose final response. On acceptance serve current_draft -- the text
        # that converged with verify_response. This is identical to the original
        # draft_response when convergence happens on iteration 1, but correct on
        # a later iteration, where the original draft was already replaced by a
        # verify response (so serving draft_response would return rejected text).
        if draft_accepted:
            final_response = current_draft
        else:
            final_response = verify_response

        total_ms = (time.time() - total_start) * 1000

        result = SpeculativeResult(
            final_response=final_response,
            draft_response=draft_response,
            verify_response=verify_response,
            draft_model=self._draft_model,
            verify_model=self._verify_model,
            draft_accepted=draft_accepted,
            iterations=iterations,
            total_latency_ms=round(total_ms, 1),
            draft_latency_ms=round(draft_latency_total, 1),
            verify_latency_ms=round(verify_latency_total, 1),
            convergence_score=round(convergence, 4),
        )
        self._last_result = result

        logger.info(
            "Speculative generation: draft_accepted=%s, iterations=%d, "
            "convergence=%.3f, latency=%.0fms",
            draft_accepted, iterations, convergence, total_ms,
        )
        return result

    # ------------------------------------------------------------------
    # Status
    # ------------------------------------------------------------------

    def get_status(self) -> dict:
        """Return current status for API consumption."""
        last = None
        if self._last_result is not None:
            r = self._last_result
            last = {
                "draft_model": r.draft_model,
                "verify_model": r.verify_model,
                "draft_accepted": r.draft_accepted,
                "iterations": r.iterations,
                "convergence_score": r.convergence_score,
                "total_latency_ms": r.total_latency_ms,
            }
        return {
            "enabled": self._enabled,
            "draft_model": self._draft_model,
            "verify_model": self._verify_model,
            "max_iterations": self._max_iterations,
            "convergence_threshold": self._convergence_threshold,
            "last_result": last,
        }


# ---------------------------------------------------------------------------
# Module-level singleton
# ---------------------------------------------------------------------------

SPECULATIVE_AVAILABLE = True

try:
    speculative_generator = SpeculativeGenerator()
except Exception as _init_err:
    logger.error("Failed to initialize SpeculativeGenerator: %s", _init_err)
    speculative_generator = None
    SPECULATIVE_AVAILABLE = False
