#!/usr/bin/env python3
"""
VERIFICATION ENGINE -- OPTI-OIGNON v1.5.0

Moteur de verification de code avec boucle generate-execute-verify-fix.

Cycle:
    1. Execute the code generated by the LLM
    2. Si erreur, analyse via StructuredOutputEngine + CodeVerification
    3. Generate a fix via the LLM
    4. Re-execute et boucle (max N iterations)

Integre le code_executor (sandbox) et le structured_output_engine
(analyse structuree des erreurs).

Author: Leon
"""

import logging
import re
import time

from pydantic import BaseModel

logger = logging.getLogger(__name__)

# Import conditionnel du code executor
try:
    from .code_executor import CodeBlock
    from .code_executor import code_executor as _default_code_executor
    CODE_EXECUTOR_AVAILABLE = True
except ImportError:
    CODE_EXECUTOR_AVAILABLE = False
    _default_code_executor = None
    CodeBlock = None

# Import conditionnel du structured output engine
try:
    from .structured_output import (
        CodeVerification,
        StructuredOutputEngine,
    )
    from .structured_output import (
        structured_output_engine as _default_structured_engine,
    )
    STRUCTURED_OUTPUT_AVAILABLE = True
except ImportError:
    STRUCTURED_OUTPUT_AVAILABLE = False
    _default_structured_engine = None
    StructuredOutputEngine = None
    CodeVerification = None


# Regex pour extraire les blocs de code des reponses LLM
_CODE_BLOCK_RE = re.compile(
    r"```(\w*)\s*\n(.*?)```",
    re.DOTALL,
)

# Aliases de langages supportes
_LANGUAGE_ALIASES = {
    "python": "python",
    "python3": "python",
    "py": "python",
    "r": "r",
    "rlang": "r",
}


class VerificationIteration(BaseModel):
    """Detail of ae iteration de verification."""
    iteration: int
    success: bool
    error: str = ""
    fix_applied: str = ""
    execution_time: float = 0.0


class VerificationResult(BaseModel):
    """Resultat final de la boucle de verification."""
    status: str  # "passed", "fixed", "failed"
    final_code: str
    language: str
    iterations: int
    execution_output: str = ""
    errors_encountered: list[str] = []
    fixes_applied: list[str] = []
    iteration_details: list[VerificationIteration] = []
    total_time: float = 0.0


class VerificationEngine:
    """Moteur de verification avec boucle generate-verify-fix.

    Execute le code, detecte les erreurs, demande un correctif au LLM,
    et re-execute. Le cycle se repete jusqu'au succes ou au max d'iterations.
    """

    # Default model for analysis and fixes
    DEFAULT_MODEL = "qwen3-coder:30b"

    def __init__(
        self,
        structured_engine=None,
        code_exec=None,
        max_iterations: int = 3,
    ):
        """Initialize the verification engine.

        Args:
            structured_engine: Instance de StructuredOutputEngine (ou None pour le singleton)
            code_exec: Instance de CodeExecutor (ou None pour le singleton)
            max_iterations: Nombre max de tentatives de correction
        """
        self._structured_engine = structured_engine
        self._code_exec = code_exec
        self._max_iterations = max(1, max_iterations)

    @property
    def structured_engine(self):
        """Acces au moteur de sortie structuree (lazy)."""
        if self._structured_engine is not None:
            return self._structured_engine
        if STRUCTURED_OUTPUT_AVAILABLE:
            return _default_structured_engine
        return None

    @property
    def code_exec(self):
        """Acces au code executor (lazy)."""
        if self._code_exec is not None:
            return self._code_exec
        if CODE_EXECUTOR_AVAILABLE:
            return _default_code_executor
        return None

    @property
    def available(self) -> bool:
        """Check that dependencies are available."""
        return self.code_exec is not None

    def verify_and_fix(
        self,
        code: str,
        language: str,
        original_question: str = "",
        model: str = "",
        timeout: int = 30,
    ) -> VerificationResult:
        """Execute le code, analyse les erreurs, tente des corrections.

        Args:
            code: Code source a verifier
            language: Langage ("python" ou "r")
            original_question: Question originale de l'utilisateur (contexte)
            model: Modele LLM pour l'analyse et les correctifs
            timeout: Timeout d'execution en secondes

        Returns:
            VerificationResult avec le code final, statut et historique
        """
        start_time = time.time()
        _model = model or self.DEFAULT_MODEL
        errors_encountered = []
        fixes_applied = []
        iteration_details = []

        # Verification des prerequis
        if not code or not code.strip():
            return VerificationResult(
                status="failed",
                final_code=code,
                language=language,
                iterations=0,
                errors_encountered=["Code vide"],
                total_time=0.0,
            )

        if self.code_exec is None:
            return VerificationResult(
                status="failed",
                final_code=code,
                language=language,
                iterations=0,
                errors_encountered=["Code executor non disponible"],
                total_time=0.0,
            )

        # Normaliser le langage
        language = _LANGUAGE_ALIASES.get(language.lower(), language.lower())
        if language not in ("python", "r"):
            return VerificationResult(
                status="failed",
                final_code=code,
                language=language,
                iterations=0,
                errors_encountered=[f"Langage non supporte pour verification: {language}"],
                total_time=0.0,
            )

        current_code = code
        last_output = ""

        for iteration in range(1, self._max_iterations + 1):
            iter_start = time.time()
            logger.info(f"Verification iteration {iteration}/{self._max_iterations} ({language})")

            # Executer le code
            try:
                result = self.code_exec.execute(
                    code=current_code,
                    language=language,
                    timeout=timeout,
                )
            except Exception as e:
                error_msg = f"Erreur execution: {e}"
                errors_encountered.append(error_msg)
                iteration_details.append(VerificationIteration(
                    iteration=iteration,
                    success=False,
                    error=error_msg,
                    execution_time=time.time() - iter_start,
                ))
                break

            last_output = result.stdout.strip()

            # Succes a this iteration
            if result.success:
                status = "passed" if iteration == 1 else "fixed"
                total_time = time.time() - start_time

                iteration_details.append(VerificationIteration(
                    iteration=iteration,
                    success=True,
                    execution_time=time.time() - iter_start,
                ))

                logger.info(
                    f"Verification {status}: iteration {iteration}, "
                    f"{total_time:.1f}s total"
                )

                return VerificationResult(
                    status=status,
                    final_code=current_code,
                    language=language,
                    iterations=iteration,
                    execution_output=last_output,
                    errors_encountered=errors_encountered,
                    fixes_applied=fixes_applied,
                    iteration_details=iteration_details,
                    total_time=total_time,
                )

            # Echec: collecter l'erreur
            error_text = result.stderr.strip() or result.error_message or "Unknown error"
            errors_encountered.append(f"Iteration {iteration}: {error_text}")

            iteration_details.append(VerificationIteration(
                iteration=iteration,
                success=False,
                error=error_text,
                execution_time=time.time() - iter_start,
            ))

            # Si it is la derniere iteration, pas de tentative de fix
            if iteration >= self._max_iterations:
                break

            # Tenter un correctif via LLM
            fixed_code = self._attempt_fix(
                code=current_code,
                error=error_text,
                language=language,
                original_question=original_question,
                model=_model,
                iteration=iteration,
            )

            if fixed_code and fixed_code != current_code:
                fixes_applied.append(
                    f"Iteration {iteration}: {error_text[:100]}"
                )
                current_code = fixed_code
                logger.info(f"Fix applique (iteration {iteration})")
            else:
                logger.warning(
                    f"No fix generated (iteration {iteration})"
                )
                break

        # Toutes les iterations echouees
        total_time = time.time() - start_time
        logger.warning(
            f"Verification echouee apres {len(iteration_details)} iterations, "
            f"{total_time:.1f}s total"
        )

        return VerificationResult(
            status="failed",
            final_code=current_code,
            language=language,
            iterations=len(iteration_details),
            execution_output=last_output,
            errors_encountered=errors_encountered,
            fixes_applied=fixes_applied,
            iteration_details=iteration_details,
            total_time=total_time,
        )

    def _attempt_fix(
        self,
        code: str,
        error: str,
        language: str,
        original_question: str,
        model: str,
        iteration: int,
    ) -> str | None:
        """Tente de corriger le code via le LLM.

        Utilise d'abord le StructuredOutputEngine pour analyser l'erreur,
        puis demande un correctif au LLM.

        Returns:
            Code corrige ou None si echec
        """
        # Etape 1: Analyse structuree de l'erreur (optionnelle)
        analysis_hint = ""
        if self.structured_engine is not None and CodeVerification is not None:
            try:
                analysis_result = self.structured_engine.generate_structured(
                    messages=[{
                        "role": "user",
                        "content": (
                            f"Analyze this {language} code error.\n\n"
                            f"Code:\n```{language}\n{code}\n```\n\n"
                            f"Error:\n{error}"
                        ),
                    }],
                    schema=CodeVerification,
                    model=model,
                    temperature=0.0,
                )
                if analysis_result.success and analysis_result.data:
                    cv = analysis_result.data
                    analysis_hint = (
                        f"\nError analysis: type={cv.error_type}, "
                        f"message={cv.error_message}, "
                        f"suggested_fix={cv.suggested_fix}"
                    )
            except Exception as e:
                logger.debug(f"Analyse structuree echouee: {e}")

        # Etape 2: Generer le correctif via prompt classique
        fix_messages = self._build_fix_prompt(
            code=code,
            error=error,
            language=language,
            original_question=original_question,
            iteration=iteration,
            analysis_hint=analysis_hint,
        )

        try:
            # Import local pour eviter les cycles
            import ollama as _ollama

            response = _ollama.chat(
                model=model,
                messages=fix_messages,
                options={"temperature": 0.0},
            )

            response_text = response.message.content or ""

            # Extraire le code corrige de la reponse
            code_blocks = self._extract_code_blocks(response_text, language)
            if code_blocks:
                return code_blocks[0]

            # Fallback: si la reponse entiere ressemble a du code
            if self._looks_like_code(response_text, language):
                return response_text.strip()

            return None

        except Exception as e:
            logger.warning(f"Erreur generation correctif: {e}")
            return None

    def _build_fix_prompt(
        self,
        code: str,
        error: str,
        language: str,
        original_question: str,
        iteration: int,
        analysis_hint: str = "",
    ) -> list[dict]:
        """Build the prompt to request a fix from the LLM.

        Args:
            code: Code source en erreur
            error: Message d'erreur
            language: Langage du code
            original_question: Question originale (contexte)
            iteration: Numero de l'iteration courante
            analysis_hint: Indication de l'analyse structuree (optionnel)

        Returns:
            Liste de messages au format Ollama
        """
        lang_name = "Python" if language == "python" else "R"
        context_part = ""
        if original_question:
            context_part = f"\nOriginal task: {original_question}\n"

        system_msg = (
            f"You are a {lang_name} code debugger. "
            f"Fix the code below based on the error message. "
            f"Respond ONLY with the corrected code in a ```{language} block. "
            f"Do not explain, do not add comments about the fix. "
            f"The code must be complete and runnable."
        )

        user_msg = (
            f"This {lang_name} code has an error (attempt {iteration}):{context_part}\n"
            f"Code:\n```{language}\n{code}\n```\n\n"
            f"Error:\n{error}"
        )

        if analysis_hint:
            user_msg += f"\n{analysis_hint}"

        return [
            {"role": "system", "content": system_msg},
            {"role": "user", "content": user_msg},
        ]

    def _extract_code_blocks(self, text: str, language: str) -> list[str]:
        """Extract code blocks from an LLM response.

        Cherche les blocs fences ```lang ... ``` correspondant au langage,
        ou des blocs sans tag de langage.

        Args:
            text: Texte contenant potentiellement des blocs de code
            language: Langage cible ("python" ou "r")

        Returns:
            Liste de codes extraits (strings)
        """
        blocks = []
        for match in _CODE_BLOCK_RE.finditer(text):
            raw_lang = match.group(1).strip().lower()
            code = match.group(2).rstrip()

            # Normaliser le tag de langage
            normalized = _LANGUAGE_ALIASES.get(raw_lang, raw_lang)

            # Accepter si langage correspond ou pas de tag
            if normalized == language or not raw_lang:
                if code.strip():
                    blocks.append(code)

        return blocks

    @staticmethod
    def _looks_like_code(text: str, language: str) -> bool:
        """Heuristique: le texte ressemble-t-il a du code executable?

        Args:
            text: Texte a analyser
            language: Langage attendu

        Returns:
            True si le texte ressemble a du code
        """
        if not text or len(text.strip()) < 10:
            return False

        # Enlever les blocs markdown eventuels
        cleaned = text.strip()
        if cleaned.startswith("```"):
            return False  # Devrait etre gere par _extract_code_blocks

        if language == "python":
            indicators = ["import ", "def ", "class ", "print(", "for ", "if ", "="]
        elif language == "r":
            indicators = ["library(", "<-", "function(", "c(", "data.frame("]
        else:
            return False

        matches = sum(1 for ind in indicators if ind in cleaned)
        return matches >= 2

    def verify_response_code_blocks(
        self,
        response_text: str,
        original_question: str = "",
        model: str = "",
        timeout: int = 30,
    ) -> list[VerificationResult]:
        """Check all executable code blocks in an LLM response.

        Extract Python and R blocks from the response, execute and
        verify each one.

        Args:
            response_text: Complete LLM response
            original_question: Original question (context)
            model: Model for fixes
            timeout: Timeout per block

        Returns:
            Liste de VerificationResult (un par bloc verifie)
        """
        if self.code_exec is None:
            return []

        results = []

        # Extraire les blocs depuis la reponse
        for match in _CODE_BLOCK_RE.finditer(response_text):
            raw_lang = match.group(1).strip().lower()
            code = match.group(2).rstrip()

            # Normaliser
            lang = _LANGUAGE_ALIASES.get(raw_lang, raw_lang)

            # Ne verifier que Python et R
            if lang not in ("python", "r"):
                continue
            if not code.strip() or len(code.strip()) < 5:
                continue

            result = self.verify_and_fix(
                code=code,
                language=lang,
                original_question=original_question,
                model=model,
                timeout=timeout,
            )
            results.append(result)

        return results


# -- Singleton --
verification_engine = VerificationEngine()
